In [1]:
import numpy as np

In [26]:
def metryka_minkowskiego(x,y,p):
    if p >=1 and p != float('inf'):
        wynik = (np.sum((abs(x-y))**p))**(1/p)
    elif p < 1 and p >= 0:
        wynik = np.sum(abs((x-y))**p)
    elif p == float('inf'):
        wynik = np.max(abs(x-y))
    return wynik

def macierz_odleglosci(x,p):
    rozmiar = len(x)
    D = np.zeros((rozmiar,rozmiar))
    for i in range(len(x)):
        for j in range(i,len(x)):
            D[j,i] = D[i,j] = metryka_minkowskiego(x[i],x[j],p)
    return print(f"Macierz odległości dla p = {p} wygląda następująco:\n{np.round(D,2)},\na średnica zbioru:\n{np.max(D)}")

def odleglosc_miedzy_zbiorami(x,y,p):
    rozmiar_x = len(x)
    rozmiar_y = len(y)
    D = np.zeros((rozmiar_x,rozmiar_y))
    for i in range(len(x)):
        for j in range(len(y)):
            D[i,j] = metryka_minkowskiego(x[i],y[j],p)
    return print(f'Odległośc dla p = {p} między tymi zbiorami wynosi:\n{np.min(D)}')

x = np.round(np.random.random_sample(10)*10)
y = np.round(np.random.random_sample(10)*10)
z = np.round(np.random.random_sample(10)*10)
w = np.round(np.random.random_sample(10)*10)

a = np.round(np.random.random_sample(10)*10)
b = np.round(np.random.random_sample(10)*10)
c = np.round(np.random.random_sample(10)*10)
d = np.round(np.random.random_sample(10)*10)

X = np.array([x,y,z,w])
Y = np.array([a,b,c,d])

macierz_odleglosci(X,5)

macierz_odleglosci(Y,2)

odleglosc_miedzy_zbiorami(X,Y,3)

Macierz odległości dla p = 5 wygląda następująco:
[[ 0.    5.6  10.4   6.86]
 [ 5.6   0.   10.22  6.36]
 [10.4  10.22  0.    6.59]
 [ 6.86  6.36  6.59  0.  ]],
a średnica zbioru:
10.404948191522992
Macierz odległości dla p = 2 wygląda następująco:
[[ 0.   15.78 10.1  14.56]
 [15.78  0.   14.93 16.28]
 [10.1  14.93  0.   14.42]
 [14.56 16.28 14.42  0.  ]],
a średnica zbioru:
16.278820596099706
Odległośc dla p = 3 między tymi zbiorami wynosi:
6.333025531362916

In [28]:
test = "abecadlo"
test

'abecadlo'

In [30]:
test[:-4]

'abec'

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('iris.csv')

In [3]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
df.query('species == "setosa"')

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [2]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('northwind.db')

query = "select * from categories"
pd.read_sql_query(query, conn)

,CategoryID,CategoryName,Description,Picture
0,1,Beverages,"Soft drinks, coffees, teas, beers, and ales",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
1,2,Condiments,"Sweet and savory sauces, relishes, spreads, an...",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
2,3,Confections,"Desserts, candies, and sweet breads",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
3,4,Dairy Products,Cheeses,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
4,5,Grains/Cereals,"Breads, crackers, pasta, and cereal",b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
5,6,Meat/Poultry,Prepared meats,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
6,7,Produce,Dried fruit and bean curd,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...
7,8,Seafood,Seaweed and fish,b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00...

In [ ]:
pd.